### ISSUE TITLE
 Sally Face dont work! Help!

### ISSUE THREAD

**Issue by cacarasa** [bbepis/XUnity.AutoTranslator#105]
I dont know why dont work with the game....
Reipatcher load the plugin perfectly, i installed same other games but in this one dont work

thanks in advance

**Comment by gravydevsupreme** [comment]
Greetings,

I took a look at the game. It seems it is using IMGUI for UI purposes, probably because it is based on [Adventure Creator](https://adventurecreator.org). However, it seems the later versions of Unity's (2019+) implementation of IMGUI differs substantially from previous versions, which means the hooking mechanism fails (IMGUI still needs to be actively enabled in the [config file](https://github.com/bbepis/XUnity.AutoTranslator#configuration), but this will fail until the next version is released).

Given that IMGUI is somewhat important to this plugin since it is oft used for other plugin UIs, this is something I am going to fix in the next version.

However, don't expect this fix to work particularly well in this game because:
 1. IMGUI is a legacy technology that really should not be used in modern Unity games.
 2. This game really stretches the limits of what you can actually do with IMGUI, using it in ways that were not intended.

Bugs you are likely to see when I get a fix in:
 * Positioning issues. Sometimes a text will appear on two lines instead of one, even though the original text was on one line.
 * Rich text issues. While IMGUI supports the concept of "rich text" for IMGUI, this plugin does not due to performance reasons. This means you run the risk of seeing markup and broken translations in the game (to be fair I don't actually know if rich text is used in this game).

**Comment by cacarasa** [comment]
Ah I understand the problem. Thank you very much for caring and trying to fix it.

**Comment by gravydevsupreme** [comment]
Hi, the latest version should now support the IMGUI used in this game. Remember to explicitly enable it in the config file.

**Comment by cacarasa** [comment]
amazing!!! thank you very much!!!

**Comment by cacarasa** [comment]
Works!!! you are a hero!

**Comment by gravydevsupreme** [comment]
Glad to hear that it worked. :)
