### ISSUE TITLE
Any possibility for this to be in VR?

### ISSUE THREAD

**Issue by ethanccss** [bbepis/XUnity.AutoTranslator#106]
Works when played normally but in games with vr the subtitles aren't displayed.  All it needs is for the text to display at the bottom of the headset! Thanks for your hard work.

**Comment by gravydevsupreme** [comment]
This plugin doesn't do anything as fancy as displaying subtitles. It just changes text from one language to another.

If you talking about KK, HS2, EC or AI Girl, then [this repository](https://github.com/DeathWeasel1337/KK_Plugins) hosts the code that handles subtitles.

I've tried these *games* in VR as well (albeit quite a while ago), but back then my experience was the same: Subtitles did not work properly and sometimes when too many lines were displayed it would actually block the VR camera view.

I assume the subtitles plugin probably has never been optimized to work for VR.

I would encourage you to make an issue in his repository instead. I am going to close this issue since this is unrelated to this plugin.
