### ISSUE TITLE
DeepL translation

### ISSUE THREAD

**Issue by mora145** [bbepis/XUnity.AutoTranslator#113]
Hi, folks. Thank you, thank you very much for your work. You really make life easier for many of us.

I am writing to you because I am trying to configure your software so that you can use the translator "DeepL" (https://www.deepl.com/translator), from English to Spanish. But when I switch to custom and enter the url in the appropriate line, it still does nothing. 
Could you help me with this?

**Comment by gravydevsupreme** [comment]
Greetings,

Custom Translate will not work like that. It is mainly an option that allow you to develop your own HTTP-based service that the plugin can interact with, as is also explained in the documentation.

[As for DeepL support](https://github.com/bbepis/XUnity.AutoTranslator/issues/36): It is certainly possible to implement a translator plugin that supports this.

I've looked a bit into the service myself by found the resulting plugin to be somewhat unstable, often with failing requests. Haven't look much more into it since then.

**Comment by gravydevsupreme** [comment]
Now supported.
