### ISSUE TITLE
Add DeepL

### ISSUE THREAD

**Issue by Terell2018** [bbepis/XUnity.AutoTranslator#135]
I just wonder it you could add deepl translate. i was copy and paste from the deepl translate and i feels like deepl translate is better than bing and google translate. you can also download DeepL translator software and you don't need to login.

https://www.deepl.com/translator

**Comment by gravydevsupreme** [comment]
I am certainly aware that DeepL is on another level when it comes to machine TL.

I did try to implement something like this in the past but for some reason it was very unstable.

Also, there is technical issues with many of the mono runtimes that is used in many "older" Unity games (KK included here) that causes such a plugin to simply not work due to lack of TLS support.

Also, there's a tiny bit of hesitation in my head over just releasing something like that because of the target. DeepL not being some massive corporation like Google or Microsoft, where any additional activity is just a drop in the ocean.
