### ISSUE TITLE
Untranslated text not being replaced with translated text

### ISSUE THREAD

**Issue by Fealow** [bbepis/XUnity.AutoTranslator#151]
I'm having an issue with a game called Itazura Kyouaku (NSFW warning). I can see that the game is able to grab and translate text as dialogue translations show up in the auto generated translations file. However, the in game dialogue text is not getting replaced with those translations. I also can't bring up the Alt + 0 menu as when i try to it flashes on screen for a split second then disappears

What makes this even more confusing is that UI element translations are successfully replacing the original text in game. It's just dialogue texts don't work. Hope that makes sense.

**Comment by Fealow** [comment]
I found this error in the bepinex console log when trying to open the Alt +0 menu. Hopefully it helps in figuring out the issue here.

https://imgur.com/ltaaHET

**Comment by gravydevsupreme** [comment]
Hm, seems I have missed this issue entirely. I apologize, but it is because I am for some reason not getting notifications.

Lucky for you, I just fixed this in relation to an unrelated request.

[XUnity.AutoTranslator-BepIn-5x-4.14.0-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5938816/XUnity.AutoTranslator-BepIn-5x-4.14.0.zip)
