### ISSUE TITLE
Can remove the delay of Manual Translation?

### ISSUE THREAD

**Issue by orangespoons** [bbepis/XUnity.AutoTranslator#161]
After automatic translation, I did manual translation by editing the text file.
The translation is good, but there is a delay for about a second. What should I do with this?

Game: Spice and Wolf VR 2
used Il2cpp BepInEx, Il2cpp XUnity.AutoTranslator.
lang: ja(japanese) to ko(korean)

**Comment by gravydevsupreme** [comment]
It should be immediate if pre-translated, unless text is displayed partially during an entry animation. In that case you can try setting `GeneratePartialTranslations=True`.

**Comment by orangespoons** [comment]
@gravydevsupreme 
Thanks.
I tried that option, but it doesn't work.
I'll attach the video I recorded.

[https://youtu.be/_My5k_XeIb8](https://youtu.be/_My5k_XeIb8)
0:00~1:03: Already loaded once, then went to the menu and then loaded again.
1:04~: This is the first time load a game after I turn it on.

There is a delay when I load the game for the fist time after I turn on the game, but once I load it, there is no problem.
I have a problem because I have to load the text each time I turn on the game.

**Comment by gravydevsupreme** [comment]
I can't really see a delay in text display.

There does appear to be some FPS lag at 1:04 and later, is that what you're referring to?

**Comment by orangespoons** [comment]
@gravydevsupreme 
Yes, that's right.
That FPS Lag only occurs when the subtitles are loaded first time. (1:04~)

**Comment by orangespoons** [comment]
https://ibb.co/hYNWQ2P
here's game directory and the location of the subtitle file.
Is the Asset being included in the StreamingAssets folder occured FPS Lag?

**Comment by orangespoons** [comment]
@gravydevsupreme 
My language uses a different font from the basic built-in font. Can FPS lag occur if the font has a large texture size?

**Comment by gravydevsupreme** [comment]
I am having a hard time answering this. Could be the font, but I doubt it is due to the size, since the Japanese character set itself is also quite large. Could be related to dynamic loading of such a character set, though. (if that is a thing in later versions of TextMesh Pro). I guess that theory might be reinforced if it is only the first time individual characters are being shown that the lag occurs. You could test if the lag also occurs if you simply replace all translations with the same resulting translation and see if the same lag occurs on subsequent displays.

That being said, I do find it odd that the game, as it uses TMP is even able to display Hangul, given that you generally need to build a custom character sheet for it during game development. (The developers would never have included a character sheet for Hangul given its required additional size.

It being IL2CPP doesn't help the matter here, since I have only really tested the IL2CPP version of the plugin in two different games.

**Comment by orangespoons** [comment]
@gravydevsupreme 
Thanks. your guess is right. individual characters are being shown that the lag occurs.
There was someone else's help to insert the Korean TTF font.
So I change the ttf font into SDF font, problem has been solved.

Thank you for your help!
