### ISSUE TITLE
zh-cn zh-tw 

### ISSUE THREAD

**Issue by halulin** [bbepis/XUnity.AutoTranslator#2]
it will take chinese as japanese,so it will translate many times.

**Comment by gravydevsupreme** [comment]
Two things:

 1. Which version was this a problem in? From 3.3.0+, an anti-spam safeguard was implemented that *SHOULD* prevent the exact thing that is described here. Basically, it is the function "IsTranslatable":

```C#
      private bool IsTranslatable( string str )
      {
         return TextHelper.ContainsJapaneseSymbols( str ) && str.Length <= Settings.MaxCharactersPerTranslation && !_translatedTexts.Contains( str );
      }
```

As you can can see, there is a check that disallows the plugin from translating something that is has already translated something else into. (the exact solution described by Tidyzq, except it is in a different method).

 2. I see your point about ContainsJapanese. Tbh, I hope there is a better way to implement this, but the check is rather important right now because often games outputs a crapton of trash to text UI (depending on the game!), that there is no meaning in translating.

Here's a solution I see. If the FromLanguage is ja(-JP), then the check will be made. If we really want this to be generic, we should consider adding a check for languages that uses different alphabets. Perhaps this is overkill though. :)

**Comment by halulin** [comment]
i dont know . almost every autotranslator plugins use google has this bug,like cm3d2's autotranslator in hongfire.
  but in zodgame forum, someone  said add [cn] behinde translated text can fix it.
also they add baidu to translate text.
https://github.com/xddxdd/CM3D2.AutoTranslate
this is link

**Comment by gravydevsupreme** [comment]
Could you try the following version and report back with whether or not you have the same problem, as you previously reported?

[XUnity.AutoTranslator-IPA-2.3.2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/1964259/XUnity.AutoTranslator-IPA-2.3.2.zip)
[XUnity.AutoTranslator-BepIn-2.3.2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/1964260/XUnity.AutoTranslator-BepIn-2.3.2.zip)

The fix Tidyzq suggested is absolutely present in this version (although it should have been present in 2.3.0 as well). In addition I have changed the "ContainsJapaneseCharacters" check to a check that is based on the "FromLanguage" param.

**Comment by halulin** [comment]
i had try ,but still......

**Comment by gravydevsupreme** [comment]
Then I will need you to be very specific about the problem you are facing and provide me with steps to reproduce, because when I test it, it works. It works in the sense that nothing is being re-translated twice.

There is a problem in KK, with the font being used. (apparently it is unable to display some of the required kanji).

**Comment by Tidyzq** [comment]
Actually, i am using 2.3.0 with IPA version, but the problem occurs as usual.

I'm sorry because it is hard to give you a retrieval path to test it as the conversation text is random in the game( the game is Koikatu from Illusion ), and i can't tell which ui component the game is using.

All i can observe from it is that: no error message printed in the IPA console, and the http request did send to google translation server.

![default](https://user-images.githubusercontent.com/10173739/39483269-654180b6-4da4-11e8-9926-7992a598eabf.PNG)

The screenshot above is part of my `_AutoGeneratedTranslations.zh-tw`, as you can see the text wrapped in red is exactly the same, and the second one takes it as untranslated and re-translated it again.

The text being re-translated is `“今天將會是美好的一天”`, you can set it as the translated text of some words, restart the game, and try if the problem will come up. But again, i don't know which ui component the game is using, so maybe you'll need to try them all.

If you can add some log points and provide me a compiled DLL, then i can provide more
info for you ( i'm sorry i don't have the compiling environment right now ).

**Comment by gravydevsupreme** [comment]
Here's another attempt. I have added an additional check to "IsTranslatable" after the text "debounce" function. 

What I suspect was happening is:
 1. Text is set to something that is not translated.
 2. Immediately afterwards it is set to something that is translated, and as such it gets "around" the initial check in the "TranslateOrQueueWebJobImmediate" method.

Could you try the following and tell me if the problem still occurs?

[XUnity.AutoTranslator-BepIn-2.3.2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/1964843/XUnity.AutoTranslator-BepIn-2.3.2.zip)
[XUnity.AutoTranslator-IPA-2.3.2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/1964844/XUnity.AutoTranslator-IPA-2.3.2.zip)

**Comment by gravydevsupreme** [comment]
Stop. I uploaded wrong file! Let me just try again

**Comment by gravydevsupreme** [comment]
Try this instead:

[XUnity.AutoTranslator-IPA-2.3.2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/1964848/XUnity.AutoTranslator-IPA-2.3.2.zip)
[XUnity.AutoTranslator-BepIn-2.3.2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/1964850/XUnity.AutoTranslator-BepIn-2.3.2.zip)

**Comment by Tidyzq** [comment]
Great! The re-translation problem never shows again!

But, it is seems it's not exactly the behavior you expected. Like a conversation dialog component, the text slowly shows character by character, the text is already been translated before the whole text is shown, as you expected to see the untranslated one.

In addition, in such case as text shows character by character, the `ToggleTranslation` method is not working, and the IPA console gives the following error message:

```
System.NullReferenceException:
  at (wrapper managed-to-native) UnityEngine.Component:get_transform ()
  at XUnity.AutoTranslator.Plugin.Core.TranslationInfo.ResizeUI (System.Object graphic) [0x00000] in <filename unknown>:0
  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.SetText (System.Object ui, System.String text, Boolean isTranslated, XUnity.AutoTranslator.Plugin.Core.TranslationInfo info) [0x00000] in <filename unknown>:0
  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.ToggleTranslation () [0x00000] in <filename unknown>:0
  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.Update () [0x00000] in <filename unknown>:0
```

And it reminds me that all of the re-translating problem occurs in the conversation dialog!

**Comment by gravydevsupreme** [comment]
**"But, it is seems it's not exactly the behavior you expected. Like a conversation dialog component, the text slowly shows character by character, the text is already been translated before the whole text is shown, as you expected to see the untranslated one."**

This is actually OK. There is some strange behaviour going on when the text is scrolling in, and if I am able to catch a translated string immediately from my cached data, I will translate it immediately without debounce. In this case the "scrolling in" of text is actually based on the translation, and not the original untranslated text.

**In addition, in such case as text shows character by character, the ToggleTranslation method is not working, and the IPA console gives the following error message:**

Can this be consistently reproduced?

**Comment by Tidyzq** [comment]
In the Koikatu game, yes, it occurs consistently. But i can't tell if it will occurs in other games.

**Comment by gravydevsupreme** [comment]
Here's another version that I'd like you to test:

[XUnity.AutoTranslator-IPA-2.3.2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/1965158/XUnity.AutoTranslator-IPA-2.3.2.zip)
[XUnity.AutoTranslator-BepIn-2.3.2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/1965160/XUnity.AutoTranslator-BepIn-2.3.2.zip)

I suspect the problem was that there was a lot of referenced components outside of the current scene that were somehow not attached to the scene/game or whatever anymore.

**Comment by halulin** [comment]
i had try the newest version,also would re-translate
[_AutoGeneratedTranslations.zh-tw.txt](https://github.com/bbepis/XUnity.AutoTranslator/files/1965406/_AutoGeneratedTranslations.zh-tw.txt)
193 and 249  .210 and 250

**Comment by halulin** [comment]
[_AutoGeneratedTranslations.zh-tw.txt](https://github.com/bbepis/XUnity.AutoTranslator/files/1966105/_AutoGeneratedTranslations.zh-tw.txt)
3011 line(the last)
1.i always remove DynamicTranslationLoader while i use autotranlate
2.i had try,this is text......still

**Comment by halulin** [comment]
use unicode to distinguish chinese or japanese

**Comment by halulin** [comment]
Finally.it work almost perfect,text dont re-translate .but “☐” still  exist.

**Comment by halulin** [comment]
still.ignore it.can you add baidu server to translate .in zh-cn.baidu is well than google.

**Comment by Tidyzq** [comment]
@halulin The only reason why characters were rendered as "☐" is the game doesn't support the character set, you should never blame the translator.

And maybe you should use baidu to translate yourself's words.

**Comment by gravydevsupreme** [comment]
Have I missed something here?

Anyway, as Tidyzq says, the font used in the game appears to not support all Kanji, which makes them appear as squares. It's probably possibly to change that, but I would need to research it, as the way to do it would probably be different for each text framework.

As for providing Baidu... Well there's some challenges here. 

First of all, I cannot read the documentation at all. Now, this is probably not that much a problem, as I can probably rely on the CM3D2 implementation (if that implementation still works!).

Second of all, I do not know how to obtain an appId/appSecret, and I would absolutely need this in order to implement it.

If you are willing to provide me with this information, I can provide you with an email to send it to (do NOT post it here). Once I have it working, I will delete the appId/appSecret.

**Comment by halulin** [comment]
ok, I have appid

**Comment by gravydevsupreme** [comment]
Alright. Please send the appId and appSecret to mrtranslate (at) protonmail.com  (spam protected notation).

**Comment by gravydevsupreme** [comment]
I received it.

**Comment by Tidyzq** [comment]
FYI, baidu is not like google which doesn't need an appid ( i see you are sending requests to the API used by google translate extension for chrome ), you must write it in your code. So i think there is no difference between putting the appid in your code or in this issue, therefore i will leave it that way XD

**Comment by gravydevsupreme** [comment]
Thanks, but it is not needed. I have already received a key and have already have confirmed it is working. Currently working on integrating it. I removed the appId/appSecret from your above comment.

**Comment by Tidyzq** [comment]
Are you sure? Because baidu's API is not for free, you have to charge it once people actually using your plugin.

**Comment by gravydevsupreme** [comment]
I will simply implement support for Baidu translate API.

If the user of the plugin wants to use it with baidu he must provide his own appId/appSecret.

**Comment by gravydevsupreme** [comment]
Let's just say that Baidu is being for more explicit by actually requiring an appId/appSecret.

**Comment by halulin** [comment]
It works perfectly.

**Comment by halulin** [comment]
Although it also would re-translate,it Not messing up the text,so,in a sense,this bug was fix.
