### ISSUE TITLE
Can you help me create a font with Vietnamese characters. for game Pathfinder Kingmaker Definitive Edition. I'm so grateful to you for that

### ISSUE THREAD

**Issue by nonamebatbai** [bbepis/XUnity.AutoTranslator#206]
please help me . I tried to create a new font but it didn't work 
this is korea font and it works with game . How to create a font like this with Vietnamese font?
https://drive.google.com/file/d/1NFhepEj9jPrjTyEmEaayKIY8yE4YSiZJ/view?fbclid=IwAR1Vu4wwBrDH68ha_rbp-ZgP0brQPU0y0W5cDW3h3m4C3nEqc9hTWa0kPZ0

**Comment by gravydevsupreme** [comment]
It's hard to help when I do not know what you've tried, but I cannot do it for you. Not because I don't want to, but because I do not really know how, if the guide I provided https://github.com/bbepis/XUnity.AutoTranslator/issues/182#issuecomment-841540202 does not work.

The best bet is to ensure that you get the version for both TextMesh Pro and the Unity version exactly right. If you do this you have the best chance of success, but it is not absolutely guaranteed, and I do not know the details surrounding why it sometimes works and doesn't work (you'd probably need to know and have worked with TextMesh Pro in a profressional/hobby capacity for many hours in order to answer that question).

It may be a bit difficult to find the version of TextMesh Pro because you need to open the `.dll` file to look at the code.

A way to find is to open the `Unity.TextMeshPro.dll` file with `dotPeek by Jet Brains` and search for the string `version`, from where you should be able to find a hardcoded string with the version number.

**Comment by nonamebatbai** [comment]
> It's hard to help when I do not know what you've tried, but I cannot do it for you. Not because I don't want to, but because I do not really know how, if the guide I provided [#182 (comment)](https://github.com/bbepis/XUnity.AutoTranslator/issues/182#issuecomment-841540202) does not work.
> 
> The best bet is to ensure that you get the version for both TextMesh Pro and the Unity version exactly right. If you do this you have the best chance of success, but it is not absolutely guaranteed, and I do not know the details surrounding why it sometimes works and doesn't work (you'd probably need to know and have worked with TextMesh Pro in a profressional/hobby capacity for many hours in order to answer that question).
> 
> It may be a bit difficult to find the version of TextMesh Pro because you need to open the `.dll` file to look at the code.
> 
> A way to find is to open the `Unity.TextMeshPro.dll` file with `dotPeek by Jet Brains` and search for the string `version`, from where you should be able to find a hardcoded string with the version number.
