### ISSUE TITLE
crash when setting FromLanguage=fr

### ISSUE THREAD

**Issue by tsukasaroot** [bbepis/XUnity.AutoTranslator#207]
Hello, the plugin immediately go in shutdown mode when i set FromLanguage=fr, thus not translating the game.
It works fine when i set it in jp or en.

The game is on steam, noob les sans factions.

I don't know if it happen with other games or if it's only this one.

Trying to access ctrl+alt+9 and such to see if i can get any debug doesn't work either.
Only the alt+0 and alt+1 triggering UI.

If anyone got any idea!

![crash](https://user-images.githubusercontent.com/18621558/124018194-df2eef80-d9e7-11eb-9a67-d2ebd6a29a05.png)

**Comment by gravydevsupreme** [comment]
French is not supported as a source language in the plugin, because it has to perform a symbol check before sending texts to the translation service.

Currently the only language tokens a symbol check exists for are: `ja ru zh-CN zh-TW zh-Hans zh-Hant zh ko en`.

Implementing a symbol check for french is probably a simply thing, it just has not been done. 

You could theoretically set the `FromLanguage=auto` to allow the translation service to guess, but then all found texts are sent to it.

**Comment by tsukasaroot** [comment]
I close this issue as it's a normal behavior. Thanks for the clarification!
