### ISSUE TITLE
Disable 1s spam prevention delay

### ISSUE THREAD

**Issue by Vin-meido** [bbepis/XUnity.AutoTranslator#232]
Is there a possible way to disable the 1s delay mentioned in https://github.com/bbepis/XUnity.AutoTranslator/tree/master#spam-prevention

I'm trying to write and see if a translation endpoint that uses Sugoi offline translator would be viable. And since it is offline, it wouldnt mind being spammed with translation requests.

It's a bit hard to find where in the sources where this delay is introduced so I'd like to both disable it in a custom build of the dll that i could rebuild and test with, and maybe as an option in the future for specific translation backends.

**Comment by gravydevsupreme** [comment]
It's not just a 1 second delay. It is a system that waits for the text shown in the component to stabilize. For example, this "delay" also prevents translating text that appears by "scrolling in" letter-by-letter, etc. It also prevents texts that constantly change from being translated.

I'm not particularly interested in release a version without the safety valve in place, but the relevant code is this:

https://github.com/bbepis/XUnity.AutoTranslator/blob/master/src/XUnity.AutoTranslator.Plugin.Core/AutoTranslationPlugin.cs#L2287

The call to "WaitForTextStabilization" is what is causing the delay to appear, as can be seen here.

Just removing that logic may cause the plugin to shutdown, however, because there are mechanisms that will detect "bad behaviour" from games. So you will probably also need to remove all references to SpamChecker.

https://github.com/bbepis/XUnity.AutoTranslator/blob/946e2173868499b44acb78a79878528a883a0613/src/XUnity.AutoTranslator.Plugin.Core/SpamChecker.cs#L13

**Comment by Vin-meido** [comment]
Thanks! I don't think releasing a new version for it is needed, since it's the only one endpoint I'm writing and is experimental anyway. Just needed to be pointed in the right direction as the codebase is large.

I could probably just create an external plugin that patches the stabilization and spam check via harmonylib when the specific endpoint is active.
