### ISSUE TITLE
XUnity.AutoTranslator-MelonMod-5.0.0 does not work in a Unity 2019 game

### ISSUE THREAD

**Issue by Elaman0117** [bbepis/XUnity.AutoTranslator#262]
I tried BepInEx at first, but BepInEx didn't work at all in this game, even though I followed the part of the troubleshooting provided by BepInEx.
So I turned to MelonLoader because it worked fine in another Unity game I played (BoneWorks).
I used the autoinstaller provided by MelonLoader and ran the game once. After that, I installed XUnity.AutoTranslator and ran the game. The game runs fine, but the plugin cannot be loaded. I checked the console and found an error.
The screenshots of the key parts and the full text of the console have been uploaded as attachments.
Thank you for your work and help.
![Game Info Part](https://user-images.githubusercontent.com/86803919/154131931-e403f1f9-b7c4-433f-b9fa-7ae9af7e5e64.png)
![Mod Loaded Part](https://user-images.githubusercontent.com/86803919/154131961-7446d1d9-eb0b-4349-a076-7f5a5d04db7c.png)
[Console log.txt](https://github.com/bbepis/XUnity.AutoTranslator/files/8073931/Console.log.txt)

**Comment by gravydevsupreme** [comment]
Not sure this is specific to Unity 2019, but rather just this game specifically. Seems that the method that is being attempted to be called by the plugin cannot be called due to an internal error happening in the Unhollower.

I cannot speak to the reason why this occurs, because I simply have no idea. Might be worth reporting it at the unhollower repository.

https://github.com/knah/Il2CppAssemblyUnhollower

Failing code: 
https://github.com/bbepis/XUnity.AutoTranslator/blob/master/src/XUnity.AutoTranslator.Plugin.Core/PluginLoader.cs#L46

**Comment by Elaman0117** [comment]
> Seems that the method that is being attempted to be called by the plugin cannot be called due to an internal error happening in the Unhollower.
> 
> I cannot speak to the reason why this occurs, because I simply have no idea. Might be worth reporting it at the unhollower repository.
> 
> https://github.com/knah/Il2CppAssemblyUnhollower
> 
> Failing code: 
> https://github.com/bbepis/XUnity.AutoTranslator/blob/master/src/XUnity.AutoTranslator.Plugin.Core/PluginLoader.cs#L46

Thanks again for your work.
I will try to give feedback to the upper level (loader) developer.
Sorry for taking so long to reply, I've been so busy with my studies recently that I haven't paid attention to GitHub replies.
Thank you for taking the time to answer questions from community users.
