### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by leillo1975** [bbepis/XUnity.AutoTranslator#28]
There are a lot of games made with Unity that have Linux support. But I don't know if this project is compatible with my os. 
Is possible to use it on Linux. If not, can you make it?

Greetings

**Comment by ArTBoL** [comment]
I have not been able to use it

**Comment by gravydevsupreme** [comment]
This plugin does not work on Linux right now.

However, it does not have any **important** dependencies on Windows APIs, so making it compatible should not be too much trouble (I think?).

The problem lies in the installers/plugin managers. The only reasonable way to hook into the game on Linux, I think, would be through BepInEx, but I do not think that is entirely supported (yet?).

@denikson or @bbepis may be able to provide more information on when this may be supported in BepInEx, as I know there has been some effort to support it in the past.

If BepInEx were to support then I would not mind removing any Windows dependencies that exist in the plugin.

DISCLAIMER: I am not a Linux user. I do not have it installed, and have never used it for any extensive period of time.

**Comment by gravydevsupreme** [comment]
The plugin should now be compatible with Linux, as long as BepInEx is used.

**Comment by NguyenHoangHieu22GIT2** [comment]
Well I use reipatcherandautotranslator.exe, it does create a shortcut, but in linux it doesn't understand that shortcut, so if I run the shortcut, it gives me this error:

![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/133379564/6b096d39-83ad-4b76-90fa-2d225e6d789d)
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/133379564/7c5f1f11-1486-4530-8333-125dfbcd4ea6)

What should I do ? thanks
