### ISSUE TITLE
dont work with Zombotron (game)

### ISSUE THREAD

**Issue by Sirfrancis17** [bbepis/XUnity.AutoTranslator#30]
I dont know why dont work with the game Zombotron
Reipatcher load the plugin perfectly but when i open the pluguin console  (alt+0) shows queued translation=60 but served translation =0
i installed same other games but in this one dont work

**Comment by Sirfrancis17** [comment]
i try in EDGE OF ETERNITY and dont work
Is possible for this file in root folder?
UnityPlayer.dll?

**Comment by qaz1314520qaz** [comment]
Yes,i.have the same problem.you solved it?

**Comment by Sirfrancis17** [comment]
Dont. It's happened to Me in other games and it doesn't work

**Comment by qaz1314520qaz** [comment]
Yes.me too.any of games doesn't  work

**Comment by qaz1314520qaz** [comment]
Plugins works well.i creat a txt filefila and it worked

**Comment by qaz1314520qaz** [comment]
But not the auto genarate

**Comment by Sirfrancis17** [comment]
then...work manual but dont work autotranslate?

**Comment by qaz1314520qaz** [comment]
Yes.so strange. Maybe translator dll is broken?

**Comment by Sirfrancis17** [comment]
i think its a incompatibility or something...i check the panel (ctrl+0) i see the program take the strings but dont translated

**Comment by qaz1314520qaz** [comment]
Maybe,anyone have the same problem?Is this a bug or sth wrong with my computer?

**Comment by gravydevsupreme** [comment]
It seems that the requests based on the WebRequest API in the mono runtime used in this game are somehow never completing, which is why the translator plugins does not work.

Potential fixes would be:
 * Traverse the runtime to determine why the requests are being blocked and resolve the issue
 * Delegate the translation to an external process with a properly working runtime
 * Fallback to different API such as UnityWebRequest in games that support it

All of these are fairly high effort, so do not expect anything soon, unless there's a lot of demand.

**Comment by gravydevsupreme** [comment]
The latest version (4.8.1) includes a new compatibility endpoint for google translate that is capable of servicing requests in this game. Press ALT+0 to select.
