### ISSUE TITLE
Font characters problem!

### ISSUE THREAD

**Issue by hranthakobian** [bbepis/XUnity.AutoTranslator#305]
Hello

Please tell me why it takes some characters from its native font but I put mine
![2022-07-31_13-44-20](https://user-images.githubusercontent.com/21078676/182020802-04c7cbed-fac2-49f4-83a7-cc980e096b10.png)
![2022-07-31_13-45-09](https://user-images.githubusercontent.com/21078676/182020803-d59aeb4a-8688-4437-a8c2-bc2313d932d3.png)
![2022-07-31_13-45-40](https://user-images.githubusercontent.com/21078676/182020804-c2293a65-6e59-41af-806f-87ad997f8df6.png)

**Comment by Atamg1994** [comment]
you most likely use the mod that I gave, by default the Arial unitcode font is there, and the font is not the same because it is directed to English and other languages, I think so, but in turn it also supports the rest, you look on the Internet for a unitcode font with  support for your language and test it, maybe you will find what you need, if you have a mod that I gave then in the font folder there is font.ttf find a replacement for it) by experimenting

**Comment by Atamg1994** [comment]
but in general, what did you want .. so that a program that automatically translates the text also selects the font for you?  it seems to me that you want a lot ... it’s up to you to hire a team of professional translators Nada so that she translates for you with high quality and picks up the font )

**Comment by hranthakobian** [comment]
> but in general, what did you want .. so that a program that automatically translates the text also selects the font for you? it seems to me that you want a lot ... it’s up to you to hire a team of professional translators Nada so that she translates for you with high quality and picks up the font )

I just wanted the program to drop native fonts

**Comment by hranthakobian** [comment]
> you most likely use the mod that I gave, by default the Arial unitcode font is there, and the font is not the same because it is directed to English and other languages, I think so, but in turn it also supports the rest, you look on the Internet for a unitcode font with support for your language and test it, maybe you will find what you need, if you have a mod that I gave then in the font folder there is font.ttf find a replacement for it) by experimenting

Thank you for response
