### ISSUE TITLE
Add support for DeepL

### ISSUE THREAD

**Issue by carpenterisalive** [bbepis/XUnity.AutoTranslator#36]
Best than Google translator

**Comment by gapculy** [comment]
It's much better DeepL. With this I did the Dead State Reanimated translation with a lot of dialogue. Instead google translator I am constantly modifying the translated text.
If it serves as an example, this text is translated with DeepL.

**Comment by gravydevsupreme** [comment]
Hello,

DeepL has a major weakness in relation to this plugin, and it's that it is hosted on web server(s) that requires a version of SSL/TLS that the UnityEngine does not support if it is distributed with a .NET 3.x or equivalent Mono Runtime. Most, but not all, Unity games are distributed with this outdated Mono Runtime.

What does this mean? Basically that the plugin is unable to communicate with the web server in most Unity games.

Luckily there is a workaround to this. It is possible to offload the translation work to a separate process that runs a full .NET runtime. However, the infrastructure to do this is not yet implemented.

I will probably look into implementing this infrastructure in the next release, as DeepL is not the only translation service that suffers from this problem.

**Comment by LegendaryB** [comment]
I have a working version using the official DeepL (Pro) API. I'm using it for Koikatsu. I build a translation server which takes japanese as input and returns the english translation for it. Also I implemented the translation plugin which connects to my translation server. It was just a prototype so many stuff is missing. For example I also wanted to add caching of sentences because DeepL wants 0,01€ every 500 characters. Or sometimes there are smileys displayed in the dialogue. I also want to extract them before sending to DeepL because they also count as characters

**Comment by gravydevsupreme** [comment]
In that case you could probably run each character through a unicode filter and remove anything that is not considered hiragana, katakana or kanji. Frankly even whitespace might be good to remove. In my experience it often improved the translation. But at the cost of formatting of course.

That being said, this plugin already removes non-repeating whitespace on longer texts, so that would not be relevant.

I would probably be careful about piping the translations through your own server, though, due to those massive costs.

If you are interested in release a plugin like this I have a reference implementation for DeepL that gets around the TLS problems I mentioned in the previous comment. That way you can perhaps avoid piping all the requests through your own translation server.

**Comment by LegendaryB** [comment]
@gravydevsupreme Thanks for the tips regarding the character handling. I know that I need to improve many things there to make it really effective.

I would not pipe them through my server. I would release the source of my server also. My current implementation looks like this:
AutoTranslator Plugin -> calls -> My translation server which runs locally and has a DeepL pro authentication key. The server calls the DeepL Pro API to retrieve the correct translation. -> Returns it to the AutoTranslator Plugin.

So my plan was never to release a plugin which uses my DeepL Pro Account. Instead people have to get their own key to use it. Was it understandable?

Kind Regards

**Comment by gravydevsupreme** [comment]
Yeah. What I was trying to say is that there is already a built-in way to get requests served out-of-process in the plugin itself. But it doesn't currently support configuration which your scenario requires since it needs an API key.

:)

**Comment by Project-Kuroneko** [comment]
Just dropping by. The Sugoi Japanese Translator could be an interesting way to add DeepL into the translator without the need for API keys. It also offers machine-learning offline translation and though the project is very new, it's quite promising in its performance.

<iframe width="560" height="315" src="https://www.youtube.com/embed/r8xFzVbmo7k" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by gravydevsupreme** [comment]
Using something like Puppeteer to control a browser instance is certainly an interesting idea. Would likely always get around API changes and robot detection issues.

Either way, will track DeepL issue here: https://github.com/bbepis/XUnity.AutoTranslator/issues/113

**Comment by MikeCZ23** [comment]
deepl no work for me

**Comment by MFZORO** [comment]
> deepl no work for me

It worked until some point 2 days ago?

```[ERROR] Error occurred while retrieving translation. An error occurred in the pipeline.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at DeepLTranslate.ExtProtocol.ExtDeepLTranslate.<GetClientState>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---```
