### ISSUE TITLE
ezTrans Translator?

### ISSUE THREAD

**Issue by DrinkC123** [bbepis/XUnity.AutoTranslator#38]
Can you add support for ezTrans Translator? plz

**Comment by gravydevsupreme** [comment]
Apologies for late replies.

I have no idea what this translator is. Is it an online translator?

**Comment by HelloKS** [comment]
"EZTrans XP" is offline translator which translate Korean to Japanese.

It's widely used for VN in Korea since some text hooking tools utilize this for their translated text.
For example: VNR, twocontrol, Aral Trans ..etc

Since this translator can be used with dll hooking, I made simple python script for custom endpoint.
https://github.com/HelloKS/ezTransWeb

Hope this helped.

**Comment by gravydevsupreme** [comment]
Very interesting. Given how simple this seems to be to integrate with, it would probably be fairly easy to integrate with a C# plugin.

May look into this in the future.

**Comment by gravydevsupreme** [comment]
Mind if I link to your project from the README?

**Comment by HelloKS** [comment]
No, feel free to use.
