### ISSUE TITLE
 Problems with ZMAZ identifiers and html markup

### ISSUE THREAD

**Issue by Atamg1994** [bbepis/XUnity.AutoTranslator#396]
I had problems with the fact that when translating, Google translator could somehow change the html markup (add spaces, etc.)
and the problem with ZM?Z - AutoTranslator mark numerical values ​​in such a way so that later after translation they will be cached with the correct key in order to avoid re-translation
But! google translate and that could break everything
AutoTranslator is waiting for its ZM?Z back to substitute some number but google translated it into my language and AutoTranslator could not find it in the translator's cache, I see 
damage done {{A}}=нанесено урона змаз
змаз = this part was supposed to remain untranslated
and then it would be
damage done {{A}}=нанесено урона {{A}}
Sometimes AutoTranslator does not cache values ​​correctly for some reason, and therefore duplicate translations may occur with a difference only in numbers, even with TemplateAllNumberAway=True enabled
I have the option enabled
TemplateAllNumberAway=True
when translating, it creates templates
Costs {{A}} month = Cost {{A}} month
Where {{A}} is any numeric value to help shorten queries. Why translate again if you can substitute a ready-made translation.
and the line below can have these parameters in an arbitrary order (it's like enchanting on an object in what order you put it in this order, which makes a bunch of such lines in the AutoTranslator cache)
Attack Power +70\nObtain Rare Item Chance+5%\nCrit Multiplier+2%\nMartial Skill/Spiritual Skill Projectile Number Increased by 1\nMartial Skill/Spiritual Skill Range Increased by 16%\nMartial Skill/Spiritual Skill Damage Increased by 16 %\nSkill CD reduced by 1%\n<sprite=2><color=#444444>Blank attribute can be fused
See screenshots
![Screenshot_15](https://github.com/bbepis/XUnity.AutoTranslator/assets/57526178/1171c523-8ea5-46dd-8b4f-8c114faca907)
![Screenshot_16](https://github.com/bbepis/XUnity.AutoTranslator/assets/57526178/094d9236-7a0d-435b-8332-daf42bfd6785)
I wrote my own server on the js node that will correctly cache the results and thus there will be fewer requests to Google servers for translation
the last screen above was split and translated separately
html markup was removed from the translation and restored after the translation here
![Screenshot_17](https://github.com/bbepis/XUnity.AutoTranslator/assets/57526178/95a30bd9-3519-4182-ab3c-ba8785e1bfd4)
![Screenshot_18](https://github.com/bbepis/XUnity.AutoTranslator/assets/57526178/ca757f0e-9a6a-4bc1-93ec-bc435a422ff4)
So this is the best option for me so far.
works

Here I will provide how I saved the AutoTranslator translation
and how my translation server cached
[_AutoGeneratedTranslations.txt](https://github.com/bbepis/XUnity.AutoTranslator/files/11873036/_AutoGeneratedTranslations.txt)
[GoogleTranslator_v2.txt](https://github.com/bbepis/XUnity.AutoTranslator/files/11873038/GoogleTranslator_v2.txt)
by the volume of the file, you can already see how much the result of caching has decreased
and if we run an experiment
take delete cache AutoTranslator
go into the game and do the same actions, then the game will transfer again many times faster since there is already a cache on the server

download and try
let me know if my solution helped you
https://github.com/Atamg1994/nodejs-GoogleTranslator-server

**Comment by gravydevsupreme** [comment]
This plugin will NEVER send duplicate translations. If you think it does it is a misunderstanding of how it works. It may in certain situations cache what looks like similar translations, especially when it comes to rich/html text. But duplicate translations are never sent to the endpoint.

Rich/html text is handled in a special way, and when you combine it with templating away numbers, confusion may arise.

Here's how it works:
 * When the plugin detects rich text it will split it up into translatable fragments that are sent to the endpoint without rich/html text present.
 * If two identical fragments are detected during this process, only 1 translation will be sent. Even the text comes from seperate UI components. In addition, if the plugin can find a translation for any of the fragments already in the cache, this will be used instead.
 * These fragments will have their numbers templated away and you will be able to find the translated fragments (with {{A}} etc.) in the translation cache file.
 * Once all translation have been translated, the UI is updated and the final string, pieced together from the fragments will be added to the translation file with the actual numbers present (this is mainly due to a limitations in the implementation, and something I am not willing to change due to how much effort it would take).
 
What this means: You can generally just ignore all the RICH/HTML text translations in the file. They are mainly there to speed up translations if the amount of rich/html text in the game is excessive.

What could be easily done is for me to provide an option to indicate that you do not want the plugin to output the result of rich/html parsings to the translation file. Something like `CacheRichTextResults`. It would really only make sense to set this to false if the rich text in question includes a lot of numbers, like it does here.

**Comment by gravydevsupreme** [comment]
Actually, I may have been a bit wrong on it persisting the tokens. After inspecting the code, it appears it does not. Don't touch a codebase for a year, and look at what happens. You forget things.

What could be done is adding a `PersistRichTextMode`. This could either be "Fragment" or "Final" (default). If Token the rich text would not be persisted, but all fragments that made up the text would be stored instead (with proper substitution replacers such as {{A}}).

**Comment by Atamg1994** [comment]
> What could be done is adding a `PersistRichTextMode`.

thanks I will test the PersistRichTextMode option
However, I still had a problem with
zm?z as an identifier, it was translated into Russian and I saw the place of the value that should be there "змаз"

there were also problems with html tags, Google translator inside the tags could set spaces and also change the case of the tag classes
I really hope that the setting PersistRichTextMode  will help to solve this problem

**Comment by Atamg1994** [comment]
> `PersistRichTextMode`.

upd : the game 鬼谷八荒 Tale of Immortal
for her mods in workshop
uses melonloader 0.5.4
as much as I could update to version 0.5.7
if you put the latest one, all mods fall off
because to try PersistRichTextMode
I had to manually update only what is connected with this and also what is connected with zm?z keys
in general, as a result, I like the work of the new option PersistRichTextMode, it helped me
