### ISSUE TITLE
XUnity.AutoTranslator-ReiPatcher

### ISSUE THREAD

**Issue by AIWArus** [bbepis/XUnity.AutoTranslator#40]
Hello.
To translate games into Unity (VN), we use XUnity.AutoTranslator-ReiPatcher-3.6.1.
There is a small request: is it possible to make the introduction of a password to the AutoTranslator folder, to protect the translation from being copied and edited by third parties?
really need this feature.
And another small question:
Which of the ReiPatcher files can be deleted after the translation is completed so as not to damage the game?

**Comment by gravydevsupreme** [comment]
**Which of the ReiPatcher files can be deleted after the translation is completed so as to not damage the game?**

Once the binaries have been patched (ran the shortcut at least once) you should be able to remove the ReiPatcher folder and the generated shortcut along with the "SetupAutoTranslatorAndReiPatcher.exe". Do be aware that ReiPatcher will modify the UnityEngine.dll/UnityEngine.CoreModule.dll. A better approach is to use BepInEx which does not modify any files.

**Is it possible to make the introduction of a password to the AutoTranslator folder, to protect the translation from being copied and edited by third parties?**

If this is to prevent someone from *stealing* your translations then there is no technical way to implement this. As far as I know at least.

Essentially this is because the plugin can only read encrypted content if it actually has the key (password). But if it has the key (password), so does any user using the plugin.

The best that could really be done is to make modifying the translation inconvenient by not having any tooling that enables decryption outside the context of the plugin itself. But since this plugin is entirely open source, anyone could immediately see how to decrypt it through the source code and implement such a tool with a bit of copy pasting.

Besides, I'm not really sure I am sold into the idea mangling translation files through encryption is in the interest of this plugin or the philosophy behind it.
