### ISSUE TITLE
Strange translator's behavior

### ISSUE THREAD

**Issue by spiritov0d** [bbepis/XUnity.AutoTranslator#41]
Hello. I'm trying to use the translator on the recent unity game called Night Call. It's build with 2018.4.3 engine version. All was done with default settings and with the same results on 3.7.0 version of the translator using BepIn or ReiPatcher.

1)  If you run the game with options set, for example, to en -> de translation it will create _AutoGeneratedTranslations.de.txt, ok. But if you'll change final language to any other, the translator will still use "de" file regardless of its name. Yes, you have to delete the file or move it from the translations folder, simple renaming doesn't work. Only after deleting it you can run the game and new file will be generated, for example, _AutoGeneratedTranslations.ru.txt.
 
2) Some results in auto-generated translation looks different in different translation directions and it seems the translator even retranslate some string more than one time.  For example, for main menu:
```
Without translator: QUIT
With en -> de direction: QUIT=VERLASSEN and __VERLASSEN__=__VERLASSEN__ string after that. In the game it will look like: __VERLASSEN__
With en -> ru direction: QUIT=УВОЛИТЬСЯ and no other strings. In the game it will look like: _         _ (game font supports cyrillic symbols by the way).
```
Any thoughts will be appreciated.

**Comment by gravydevsupreme** [comment]
Right. 

Issue 1) is expected behaviour. It will look at all text files in that directory. The plugin in it's current state does not support multiple translation languages. With the name of the file, I know this can be a bit misleading, but I have not changed it for compatibility reasons. You can remove the {lang} parameter from the name if you find it annoying.

Issue 2) 

Took a look at the game. Turns out it uses a localization system that causes this behaviour. The "__X__" attempts to tell the developer that the text for this "translation key" could not be found.

The reason you see multiple entries in the translation log for DE is because there is no way to tell whether or not the phrase has already been translated because both languages use the same character set.

I can probably take a look to see if I can find a generic solution to this.

About cyrillics: Are you absolutely sure about this? Have you seen it work in this game? 

The problem here is that for TextMeshPro (which this game uses) the fonts must be build specifically for the game with support for the required symbols.

**Comment by spiritov0d** [comment]
Thanks for the response.
1) I got it, thanks for the explanation. I thought it could be easy to add multiple language files support like this: auto-translator checks config and if it will find that final language is "de", it will use  AutoGeneratedTranslations.de.txt. At least, substitutions works this way now. Or maybe it could check and create file for selected pair of languages, for example AutoGeneratedTranslations.en-de.txt.
2) It looks a bit recursive for me. So the translator pick up a line, translates it, integrates back, read it again, attempts to translate it again... Why it's only two cycles then and not infinite. Or it's an exception because of the used in-game localization system? 
As for the cyrillics - in the main menu Version=Версия string from auto-generated translation is visible as "_ВЕРСИЯ_", while all other strings are empty. Also, the game has only 1 font file and it has cyrillics. But it's probably the localization system fault as well. 
Anyway, it's just thoughts. If the game is using custom localization system, there is no need to update the translator, since it can possibly bring more unnecessary complexity to the code.

**Comment by gravydevsupreme** [comment]
Well the game is using a custom-built localization system, which is causing the problems. 

For the font: The reason that the version information in the bottom-left corner seems to work is because that is using a standard UGUI Text with standard Arial font. The other elements are using TextMeshPro with a custom built font.

But what you're saying is that you don't want me to try to make it compatible anyway?

**Comment by spiritov0d** [comment]
I just don't want you to spend your time on trying, if it will not benefit translator in general. First I thought it was because of translator, since the game is using new unity version, but since it's because of localization system... Well, it's entirely up to you. I would be grateful if you could take a look at it (if something can be done in reasonable amount of time). If not, it's fine too - just let me know so I could close the issue.
Anyway, thanks for helping people here, really appreciated.

**Comment by gravydevsupreme** [comment]
I can probably solve the "__" issue, but not the font issue. Don't know if that is a dealbreaker. :)

**Comment by spiritov0d** [comment]
That would be enough (I mean, fixing the "__" issue). Since almost all other languages are working fine there, people should be able to use the translator with this fix. Thanks in advance )

**Comment by gravydevsupreme** [comment]
After looking into the issue a bit further it turns out the plugin already has a feature that *should* make this game work. However, there is a bug in this feature. 

Essentially you can set `TextGetterCompatibilityMode=True` and it should work, were it not for the bug. Essentially it fools the game into thinking it has not been translated by this plugin.

The following version fixes the bug:

[XUnity.AutoTranslator-BepIn-5x-3.7.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3416215/XUnity.AutoTranslator-BepIn-5x-3.7.0.zip)

Can you confirm it works?

**Comment by spiritov0d** [comment]
Yes, it works as it should now with TextGetterCompatibilityMode=True option. Thank you )
I'll close the issue then.
