### ISSUE TITLE
Do not translate

### ISSUE THREAD

**Issue by djlaser** [bbepis/XUnity.AutoTranslator#45]
Hello
I use your Reipatcher plugin
Almost everything translates normally. But recently I ran into a problem
he translates the old version of the game, but the new one is not.
because in the old game he patched UnityEngine.dll
and in the new UnityEngine.CoreModule, there is no translation
Obviously, for translation you need to patch UnityEngine.dll
and how to do it.
Thank.
[logg.txt](https://github.com/bbepis/XUnity.AutoTranslator/files/3491484/logg.txt)

**Comment by gravydevsupreme** [comment]
Greetings,

The plugin should be able to translate Unity games of basically any version given that it uses a known UI system.

What game are we talking about here?

In addition, it seems you are using version 3.6.1 with experimental hooks (which have been deprecated). I would recommend updating to the latest version to see if the problem persists.

**Comment by djlaser** [comment]
Hello
 
This game is MilfsResort v5.1
On 3.8.1, the same logs are the same.
On MilfsResort 4.2, everything is fine
Oh, thank you.

**Comment by gravydevsupreme** [comment]
Tried out the game.

While I cannot try v4.2 because it is no longer available for download, I could try v5.1.

The reason that version does not work is because it uses a custom UI system that this plugin does not support, probably related to the [adventure engine](https://www.adventurecreator.org) it uses.

Perhaps the other v4.2 used a different UI system and that was why it worked.

While I would like to look into this engine to see how to make it work, I currently have my plate full with other things I am working on.

I will take a look at this issue once I have the required time.

**Comment by djlaser** [comment]
Hello
 
Thank You for your answer. The plugin is very good and I know.
that you're working on it. And can be another question.
Some games and apps do not have support
Cyrillic fonts, they just use the fonts installed in Windows.
If it is possible whether it will be possible to make such support.

Thanks
 with respect djlaser

**Comment by gravydevsupreme** [comment]
Well, this feature is "sort of" already supported through the configuration options `OverrideFont` and `OverrideFontTextMeshPro`.

The reason I say "sort of" is because TextMeshPro requires the fonts to be specfically build for the games, so it is difficult to replace such a font if it is not distributed with the game.

If the game does use TextMeshPro my only recommendation for now would be to try using one of the values `Fonts & Materials/LiberationSans SDF` or `Fonts & Materials/ARIAL SDF` as those may be the default fonts distributed with TextMeshPro (sometimes).

The ability to load additional fonts for TextMeshPro is not currently a priority, unless demand rises as it is a fairly high effort task.
