### ISSUE TITLE
AutoTranslator Add Feather to Enable and Disable "「 」" Setting.

### ISSUE THREAD

**Issue by Terell2018** [bbepis/XUnity.AutoTranslator#46]
I just notice that there is a different translator when you remove "[ ]" from dialogue in translate.txt
example.

With "「 」"
「今ちょっといい？　もし良かったら少しだけ俺と話さない？」="I'm just a little bit better now. If you dont mind, why dont you talk to me a little bit? 

Without "「 」"
今ちょっといい？　もし良かったら少しだけ俺と話さない？ = Can I talk to you for a second now? If you don't mind, why don't you talk to me a little bit?

**Comment by gravydevsupreme** [comment]
Just to clarify, you're talking about excluding those characters from the text to be translated to potentially improve the translation?

I suppose something like that would be possible, but do you have some evidence that this actually improves the translations with the various services?

**Comment by Terell2018** [comment]
i copy and paste both translate site systran translate and bing translate without "[ ]".

Bing translate: At all, all of a sudden, such a way of calling. Darling...... Are you satisfied with this?bit?

Systran translate: Oh, I don't know how to call it that suddenly. Darling ... is this enough?

**Comment by gravydevsupreme** [comment]
I'll probably look into experimenting a bit with this once I have some more time. It could be an interesting feature where you remove these characters before sending them to the translation endpoint and then adding them again afterwards.

I am a bit swamped in other tasks at the moment, though.

**Comment by TokcDK** [comment]
Using in own utility kind of pretranslation regex rules to extract some text or special symbols to prevent them to be broken and paste them back. For `「 」` and `"` using next regexes:
```
^\"「(.+)」\"$
^「(.+)」$
^\"(.+)\"$
```
Translating $1 here.

As I understood now in latest version 4.1 of the autotranslator text between 「 」 can be extracted and translated without this jp quotes with same kind of rule in _SplitterPatterns.en.txt:
`^「(.+)」$=「$1」`
..added `^` and `$` to make pattern more precise. 
If Im not wrong and here it is working so then this regex rule in _SplitterPatterns.en.txt must translate text without quotes and then paste quotes back to translated text. I didnt test it and only suppose because need to find game where text in this format

**Comment by Terell2018** [comment]
Do i put regex in the _SplitterPatterns.en.txt

**Comment by TokcDK** [comment]
Yes, you need to place for example `^「(.+)」$=「$1」` regex line in **_SplitterPatterns.en.txt** and then check in game if it is working as it must and translating text without jp quotation marks. See also dev's readme [part](https://github.com/bbepis/XUnity.AutoTranslator#splitter-regex) about this feature.

**Comment by Terell2018** [comment]
I just test it with google translator and it work. 
From auto-translate "See you next ... fufufu"
From google translate site "See you later ... fufufu"

**Comment by TokcDK** [comment]
As I understood from readme in latest versions place of rules was changed and now need to add rules not in `_SplitterPatterns.en.txt` but in `_AutoGeneratedTranslations.en.txt` file with translation and it must be looking like this:
`sr:"^「(.+)」$"=「$1」`

**Comment by gravydevsupreme** [comment]
The latest version of XUA (4.7.0) now has a function that allows preprocessing of text before sending it to the translator. It is a special file (like substitutions) that you can put key-value pairs into. By default the file is called `_Preprocessors.txt`.

**Comment by Terell2018** [comment]
i just wonder do i put (sr:"^「(.+)」$"=「$1」) inside the _Preprocessors.txt

**Comment by TokcDK** [comment]
Just create any txt with any name in same folder where generated\Preprocessors and other and put `sr:"^「(.+)」$"=「$1」` in this created txt.

**Comment by Terell2018** [comment]
I think i starting to understand but i am not sure, i put ^「(.+)」$=「$1」inside the _SplitterPatterns.en.txt and put sr:"^「(.+)」$"=「$1」inside the _AutoGeneratedTranslations.txt

**Comment by makkoar** [comment]
Hi. I'm trying to remove all such instances of `<noparse></noparse>` or  `<noparse></noparse><noparse></noparse>` 
because strings like this are generated
`<noparse></noparse>Have you ever pursued your dreams?=<noparse></noparse>Вы когда-нибудь следовали своей мечте?`
because similar  `<noparse></noparse>` strings are generated, and I need to do it without  `<noparse></noparse>`

I've tried doing add X lines to the beginning of the translation file

```
<noparse></noparse><noparse></noparse>=""
<noparse></noparse>=""
```

or 
`r:"^<noparse></noparse>(.+)"=$1`
in `_Preprocessors.txt`

Nothing helps, it still generates with that text `<noparse></noparse>`

**Comment by TokcDK** [comment]
> Hi. I'm trying to remove all such instances of `<noparse></noparse>` or `<noparse></noparse><noparse></noparse>` because strings like this are generated `<noparse></noparse>Have you ever pursued your dreams?=<noparse></noparse>Вы когда-нибудь следовали своей мечте?` because similar `<noparse></noparse>` strings are generated, and I need to do it without `<noparse></noparse>`
> 
> I've tried doing add X lines to the beginning of the translation file
> 
> ```
> <noparse></noparse><noparse></noparse>=""
> <noparse></noparse>=""
> ```
> 
> or `r:"^<noparse></noparse>(.+)"=$1` in `_Preprocessors.txt`
> 
> Nothing helps, it still generates with that text `<noparse></noparse>`

Common regex rule like "sr:^<noparse><\/noparse>(.+)$=<noparse><\/noparse>$1" must work.

**Comment by TokcDK** [comment]
> First: `sr:"^<noparse><\/noparse>(.+)$"=$1` Second: The result hasn't changed. "`<noparse></noparse>`" As it was generated, it is still generated. Result: `<noparse></noparse>Have you ever pursued your dreams?=<noparse></noparse>Вы когда-нибудь следовали своей мечте?`

Let me explain.
For example I make regex.txt next to autogenerated txt and add the line in regex.txt:
`sr:^<noparse></noparse>(.+)$=<noparse></noparse>$1`

If I edit and game already executing I switch into the game and press `alt+r` to update translation cache.

when the plugin check line like `<noparse><\/noparse>blabla` it will be parsed by the added regex `^<noparse><\/noparse>(.+)$` where text `blabla` will be captured as group 1 and will be sent for translation if it was not already in the exist cache. After it will be translated to `блабла` it will be first added into cache as `blabla=блабла` line and then inserted back using regex replace and line `<noparse></noparse>$1` on place of group 1 mark `$1`. In result we will get displayed text `<noparse></noparse>блабла`. `<noparse></noparse>` in this case will be ignored because it was not captured as any regex group. It was an explanation as it work when text captured by the added regex line. When you get `<noparse></noparse>blabla=<noparse></noparse>блабла` text in cache it means that the regex expression is not capturing the text and need to edit the expression and check again because there can be new line somewhere or other symbols maybe need to add `\` before some other symbols because some symbols like `[ ] \ ^ $ . | ? * + ( ).` must be escaped using `\` when they are part of capturing text.
