### ISSUE TITLE
I can't change the font and character spacing

### ISSUE THREAD

**Issue by GHORAed** [bbepis/XUnity.AutoTranslator#473]
I'm trying to translate the game using a reipatcher, but when using the Cyrillic alphabet, there is a huge distance between the characters.
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/19502839/93574014-f484-454a-9e9f-b8898fd63cea)
Original:
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/19502839/91b2b523-4d97-474a-8481-83d8e343a7d9)
I tried changing the fonts in the config file, but this does not change the font in the game. What can I do? Maybe there is a setting for the distance between characters or am I somehow changing the font incorrectly?
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/19502839/5c4ef82d-0ee8-412c-b5f2-02694e5b9c41)

**Comment by GHORAed** [comment]
I tried to install via melonmod and use font override, but with this mod the game does not start at all
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/19502839/8fbed49d-9a8a-4c7f-8c00-fb5350395947)

**Comment by Atamg1994** [comment]
FontOverride.dll will not work in the game, very old version is used TextMeshPro

**Comment by Atamg1994** [comment]
> > FontOverride.dll will not work, in the game used very old version TextMeshPro
> 
> So I can't change the font?

you can, but you will have to make a game asset and at the same time use the old version of Unity, otherwise the asset may not be suitable or use the assets that you have... but the letters will still be with a large distance between them

but another problem is where to get such an old version of TextMeshPro... without the old version, even on the old unit you can’t make a suitable asset in other words you need 1 old unity engineer 2 old TextMeshPro no other way


the mod FontOverride.dll   in which I used a dynamic font will not work here since the version of TextMeshPro is so old that there is no support for dynamic fonts

**Comment by GHORAed** [comment]
> > > FontOverride.dll will not work, in the game used very old version TextMeshPro
> > 
> > 
> > So I can't change the font?
> 
> you can, but you will have to make a game asset and at the same time use the old version of Unity, otherwise the asset may not be suitable or use the assets that you have... but the letters will still be with a large distance between them
> 
> but another problem is where to get such an old version of TextMeshPro... without the old version, even on the old unit you can’t make a suitable asset in other words you need 1 old unity engineer 2 old TextMeshPro no other way
> 
> the mod FontOverride.dll in which I used a dynamic font will not work here since the version of TextMeshPro is so old that there is no support for dynamic fonts

Okay, I got it, thanks a lot for the answer!
