### ISSUE TITLE
Inconsistent/Temporary Translation

### ISSUE THREAD

**Issue by AoiRice** [bbepis/XUnity.AutoTranslator#5]
Hello, for some strange reason this plugin only temporarily translates my game. For example, in Koikatsu I'll enter the character maker and everything will be translated, and as soon as I exit the maker the auto translation ceases. Another example of this issue is when I enter the class selector, most of the Japanese text will have been translated, and when I've started the new game or if I back out to the main menu, the translation ceases and every piece of text is back to Japanese. 
I've used this plugin before and I've never had an issue with it until now, after reinstalling Koikatsu. I appreciate any help I receive, thanks.

**Comment by TokcDK** [comment]
Yesterday I also found utilities wich is using Gautotranslation on translate.googleapis.com stopped working from time to time. After this I found G server started to return 503 error after small time of using translation function. Then I checked request on translate.googleapis.com in browser and g server said about detected suspicious traffic and temporary block. Then I attached proxy to one of using gautotrans apps and g also was blocking them quiet faster after 1-5 minutes with same 503 error.
I suppose yesterday Google started to block requests from 3rd party apps after some time. I checked several apps with same result. As I understood even spam prevention of this plugin like translation cache is not helping from blocking.

**Comment by TokcDK** [comment]
To [bbepis](https://github.com/bbepis). I still didnt test it enough but try to see [here](http://www.hongfire.com/forum/forum/hentai-lair/hentai-game-discussion/tools-and-tutorials/68499-translation-aggregator?p=6088463#post6088463) about what was changed in fresh sources of utility in target HF theme to resolve the problem and make same fix for the XUnity.AutoTranslator.
.

**Comment by AoiRice** [comment]
Interesting insights, it's great that you've got on it and investigated so quickly. I feel that it'd be a more easy solution to just add a more accurate translation site for optimization to substitute for Google Translate rather than trying to bypass Google's third party access blocking.

**Comment by notanumber6** [comment]
Is there a more accurate translation site, though?

**Comment by Scrublord1336** [comment]
Hello,

Based on @TokcDK suggestion, I have implemented a new version that sends the same "checksum" that was implemented in Translation Aggregator. In my experience it seems to be working, perhaps you are guys are willing to test it?

https://github.com/Scrublord1336/XUnity.AutoTranslator/releases/tag/2.6.0

Obviously the fix is probably a bit fragile given that it just takes them changing the way they calculate the checksum for this to break. 

PR: https://github.com/bbepis/XUnity.AutoTranslator/pull/7

I have also fixed a few other things in this PR:
 * Support for newer versions of unity engine (those including UnityEngine.CoreModule, etc. in Managed folder) (NOTE: No plugin manager supports these new versions of the engine, so it must be patched through ReiPatcher)
 * Keeps functioning if web services fails, but no requests will be sent in such scenario. Texts will simply be translated from cache
 * Disabled all concurrency for web requests
 * Changed hooking, such that if text framework fails, the others wont also fail

**Comment by lightningterror** [comment]
I gave it a go and it works.

**Comment by Himatori** [comment]
how instal?

**Comment by Scrublord1336** [comment]
I have been looking a bit further into Sinflower's fix for Translation Aggregator in order to actually understand it.

It seems that he is using two variables, something referred to as TKK. These two values are hardcoded in 2.6.0 (and Translation Aggregator), but is actually something that can be extracted directly from the gtrans web UI source.

In my experience these two values often change, which probably means they will be invalidated at some point in the future and 2.6.0 will break.

I have tried to come out ahead of that and implemented a new version 2.7.0, where I extract these two values from the gtrans web UI source. This requires some evaluation of some javascript so I have had to take in an additional dependency, Jurassic, which is a Javascript engine that can be run in Unity3D context.

Anyway, if you are willing to check it out, it is available here as well: https://github.com/Scrublord1336/XUnity.AutoTranslator/releases

I have also fixed a few other things in this release:
 * Additional installation instructions for standalone installation through ReiPatcher
 * Fixed a bug with NGUI that caused those texts not to be translated (this will be very relevant come MICONISOMI's next game)

If you want me to PR it in, please inform me of that.

**Comment by lightningterror** [comment]
Well the changes are already in the PR, since you pushed the changes on the master branch.

**Comment by Scrublord1336** [comment]
Oh, insteresting. Thought the PR refererred to a commit, not a branch. Guess you learn something new every day.

**Comment by Sinflower** [comment]
> It seems that he is using two variables, something referred to as TKK. These two values are hardcoded in 2.6.0 (and Translation Aggregator), but is actually something that can be extracted directly from the gtrans web UI source.
>
> In my experience these two values often change, which probably means they will be invalidated at some point in the future and 2.6.0 will break.

While it is true that the TKK values change (I think they change every day or even every fresh access to the website) that does in fact not tend to break the calculation, I had values from over two years ago still producing valid results.
Which brings me to

> Obviously the fix is probably a bit fragile given that it just takes them changing the way they calculate the checksum for this to break.

While here as well it is also true that a change will most likely break any system using this calculation, this calculation has been consistent for over two years (maybe longer). Fun fact, baidu uses the same calculation to produce their checksum.

In case you would like to build a more elaborate system e.g. load and execute the original javascript functions, you can find them here:
https://translate.google.com/translate/releases/twsfe_w_20180723_RC00/r/js/desktop_module_main.js
Just search for one of the large magic numbers in the calculation. As a note however, google tends to update this file and while they do not change the calculation, they change the function names.

**Comment by Scrublord1336** [comment]
Hello @Sinflower 

Thanks for the insight!

Right now the approach is simply to look at the html page, which is where the TKK is populated, but I did indeed consider also replacing the calculation with calculation that can be found in this file.

That would however, take quite a bit more effort, and I am not confident that would if they were to change the algorithm, that such an approach would be rigid enough to survive it (which would defeat the entire point).

Maybe I'll try it... for the challenge :). This function looks interesting if I could get to call it:

```js
var mx = function(a, b, c, d, e, f) {
    b = Tg("/translate_tts?ie=UTF-8&q=", Ag(b), "&tl=", c, "&total=", d, "&idx=", e, "&textlen=", b.length, jr(b), a.aa, f);
    a.K && (b += "&" + a.K);
    return b
};
```

**Comment by Scrublord1336** [comment]
@Sinflower 

Perhaps you can shed some light on something for me:

Why did Translation Aggregator stop working? To me it seems like this "checksum" implementation already existed before r190.

**Comment by Sinflower** [comment]
It did exist, however it was not used because up until recently it worked without the checksum. Additionally google now requires the cookie provided by translate.google.com to be present or else it will stop after ~50 translations.

**Comment by Sinflower** [comment]
I just looked at your current implementation of the checksum and noticed you used the first release I posed, which contained a bug in the checksum calculation. I made a mistake while converting a part of the javascript code to C++, to be precise, there was a problem with the cases inside the loop, you can find the (hopefully) correct loop below.

```cpp
for(size_t v = 0; v < r.length(); v++)
{
	int64_t A = (int32_t)r.at(v);
	if(128 > A)
		S.push_back(A);
	else
	{
		if(2048 > A)
			S.push_back(A >> 6 | 192);
		else if(55296 == (64512 & A) && v + 1 < r.length() && 56320 == (64512 & r.at(v + 1)))
		{
			A = 65536 + ((1023 & A) << 10) + (1023 & r.at(++v));
			S.push_back(A >> 18 | 240);
			S.push_back(A >> 12 & 63 | 128);
		}
		else
		{
			S.push_back(A >> 12 | 224);
			S.push_back(A >> 6 & 63 | 128);
		}

		S.push_back(63 & A | 128);
	}
}
```

**Comment by Sinflower** [comment]
Yeah if you do not use persistent HTTP connections you should not face the cookie problem, TA uses a persistent connection (used by all web based translators) which causes the problems.

As for the code, yeah that indeed looks correct, maybe I looked at an old commit.

**Comment by Scrublord1336** [comment]
Been testing this solution a bit further. It seems to work. However, if you really push it, it still starts complaining. It takes far more requests now though. I will try to reimplement the HTTP such that a session/cookie is used, and see how that goes.

**Comment by Sinflower** [comment]
I ran some stress tests on my solution (between 5 and 10 request per second I think) for around 30 min. without any problems.

**Comment by Scrublord1336** [comment]
Question regarding your implementation for the cookie: Is it simply honoring the Set-Cookie header when you call the API, and that's it? I can see you reset it every 100 requests(?).

**Comment by Sinflower** [comment]
During the first request and afterwards every 100 requests I update the "requestHeaders" variable by adding the cookies retrieved from the website, during the actual request with "WinHttpSendRequest" "requestHeaders" is used to provide all headers including the cookies.

**Comment by Scrublord1336** [comment]
Hm - are you sending this request to a special URL? I am trying this and I am definitely not getting any cookies back.

Here's an example:
```http
GET https://translate.googleapis.com/translate_a/single?client=t&dt=t&sl=ja&tl=en&ie=UTF-8&oe=UTF-8&tk=328623.228504&q=%e3%83%a9%e3%83%b3%e3%82%ad%e3%83%b3%e3%82%b0%e3%81%ab%e5%8f%82%e5%8a%a0 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
Host: translate.googleapis.com
```

```http
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
X-Frame-Options: SAMEORIGIN
Date: Sat, 28 Jul 2018 23:28:13 GMT
Pragma: no-cache
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json; charset=UTF-8
X-Content-Type-Options: nosniff
Content-Disposition: attachment; filename="f.txt"
Server: HTTP server (unknown)
X-XSS-Protection: 1; mode=block
Alt-Svc: quic=":443"; ma=2592000; v="44,43,39,35"
Accept-Ranges: none
Vary: Accept-Encoding
Content-Length: 69

[[["Join ranking","ランキングに参加",null,null,3]],null,"ja"]
```

No Set-Cookie header as I would expect.

**Comment by Sinflower** [comment]
I get the cookies from:
https://translate.google.com/

**Comment by phman112293** [comment]
again stopped working, after a certain number of words stops translating

**Comment by Scrublord1336** [comment]
Hah. Persistent HTTP connections are such a pain in Unity. Neither of their native classes support it, and the general .NET class that does support it, does not properly support HTTPS (because Mono is ****, I assume :)).

Anyway, I managed to get it working properly I think. So I now acquire the cookie at the same time that I acquire the TKK value. 

There's a lot of advantages to this:
 * It is faster, because it does not need to re-establish the HTTP connection all the time
 * I have enabled SSL by default (without certificate check) for gtrans, because the SSL handshake overhead is much smaller now that persistent connections are used

After this change, I have not seen "503 Service Unavailable" errors.

@Sinflower thanks for the help.

@phman112293 I am aware that this can happen. Perhaps you are willing to try out this unreleased version, and tell me if it works?

[XUnity.AutoTranslator-BepIn-2.8.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/2238815/XUnity.AutoTranslator-BepIn-2.8.0.zip)

**Comment by phman112293** [comment]
Thank you very much for your help, for the moment it works correctly with the version XUnity.AutoTranslator-BepIn-2.8.0 has exceeded the number of words where I stayed, anyway I inform you if an irregularity occurs.
And thanks for allowing me to be the first to try the new version

Again, thank you very much for your work and your effort

**Comment by tureg** [comment]
So what does a user with no programming knowledge (at all) do to fix this, with CM3D2? Also, I can only do Sybaris for some reason, I did the Sybaris 2 to BepInEx migration pack and used @Scrublord1336 's unreleased autotranslator above but the game crashes before launching with Bepinex for some reason

Thanks in advance

**Comment by Scrublord1336** [comment]
@tureg 

I can attempt to make this available as a UnityInjector plugin. I assume this is what is being used in that game.

**Comment by tureg** [comment]
@Scrublord1336 that would be amazing. Looking forward to it, thank you!!

**Comment by Scrublord1336** [comment]
So, the latest version does have a UnityInjector installer as well.

Right [here](https://github.com/XUnity-Development/XUnity.AutoTranslator/releases).

Few things:
 * Anything in the UnityInjector folder must be placed where ever that folder might be located. There is probably some duplicate DLLs that are also used by other plugins but this should not be a problem.
 * **It almost goes without saying but you should remove the other AutoTranslate plugin, so both does not run!!!**
 * It does work. At least it did for me. In first try, I might add.

Also worth remembering that this is a general purpose translator, it does not hook into the existing infrastructure of CM3D2 in order to only provide story translations. It will attempt to translate anything it can find that it does not consider translated, so it could have some unintended side effects. However, it is intelligent enough to allow for existing infrastructure to attempt translation before it does in most cases.
