### ISSUE TITLE
SetUpReiPatcherAndAutoTranslator crashes

### ISSUE THREAD

**Issue by larsencm** [bbepis/XUnity.AutoTranslator#50]
Here is the log

Unhandled Exception: System.InvalidCastException: Unable to cast COM object of t
ype 'System.__ComObject' to interface type 'Shell32.Shell'. This operation faile
d because the QueryInterface call on the COM component for the interface with II
D '{286E6F1B-7113-4355-9562-96B7E9D64C54}' failed due to the following error: No
 such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at XUnity.AutoTranslator.Setup.Program.CreateShortcut(String gameExePath, Str
ing shortcutName, String shortcutPath, String targetFileLocation)
   at XUnity.AutoTranslator.Setup.Program.Main(String[] args)

Please, help

**Comment by gravydevsupreme** [comment]
Hard for me to say what is causing the error, but what is going wrong here is the creation of the shortcut, which is the final step of the setup process.

So after running and generating this error you should be able to create the shortcut manually.

Take a look at this issue, which experienced the same issue:

https://github.com/bbepis/XUnity.AutoTranslator/issues/21

**Comment by larsencm** [comment]
I saw that thread. I did not understand your instructions.
*(Patch and Run).lnk is created and it is empty. How should I send it? What should be in it? What properties does it need to have?
Thank you very much for your help.

**Comment by gravydevsupreme** [comment]
It's just a shortcut. Delete the empty lnk file you have and create a new shortcut to the file "ReiPatcher\ReiPatcher.exe" located in your game directory. Then edit "Target" and "Start in" as suggested in the above issue.

**Comment by larsencm** [comment]
Oh, I see. Thank you. I will try that tonight.

**Comment by larsencm** [comment]
It worked.! Thank you!

**Comment by gravydevsupreme** [comment]
In that case, perhaps you can fill me in a little bit on your environment, since I have never been able to replicate this issue?

**Comment by larsencm** [comment]
What exactly about my environment would you like to know? I have a pretty old PC (bought it in 2015), run Windows 7. If there is a command that you would like me to run to dump into a log file, please, let me know what command to run.

**Comment by gravydevsupreme** [comment]
Well, I think Win7 is enough. Although I don't really think this is a missing API in Win7. So maybe the cause shall remain a mystery. Thanks anyway. :)

**Comment by TokcDK** [comment]
Also on Win7 always have same issue with Reipatcher version of the installer. 

If it is possible I can test and debug installer on my system to fix the problem.

**Comment by TokcDK** [comment]
It is strange. Getting the eror when using SetupReiPatcherAndAutoTranslator.exe 4.3.1 downloaded from releases. But forked latest sources and compiled SetupReiPatcherAndAutoTranslator.exe 4,3,1 from it and tested on same game folder and all installation was completed without any problems.

**Comment by TokcDK** [comment]
Here installer of 4.3.1 which was build on VC2019/W7/Release:

[SetupReiPatcherAndAutoTranslator4.3.1(VS2019_W7build).zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3619714/SetupReiPatcherAndAutoTranslator4.3.1.VS2019_W7build.zip)

**Comment by gravydevsupreme** [comment]
Perhaps you can test this one then:

[XUnity.AutoTranslator-ReiPatcher-4.4.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3622452/XUnity.AutoTranslator-ReiPatcher-4.4.0.zip)

**Comment by gravydevsupreme** [comment]
I think the reason is that W10 comes with functionality that is not available in W7 and when I reference the library that enables interacting the with the shell API, it tries to load parts of the library that does not exist.  The version I have included in my above comment removes some of the unneeded functionality.

**Comment by TokcDK** [comment]
You are right. 4.4 is working fine like posted 4.3.1 compiled in W7.

**Comment by gravydevsupreme** [comment]
Amazing. Mystery solved.

**Comment by TokcDK** [comment]
> Perhaps you can test this one then:
> 
> [XUnity.AutoTranslator-ReiPatcher-4.4.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3622483/XUnity.AutoTranslator-ReiPatcher-4.4.0.zip)
Tested some time on several different jp games and it looks like something wrong with this version. Looks like something wrong with Substitutions because they are not translating and not loading from _Substitutions.en.txt. Reverted to 4.3.1 and substitutions working there and loading from _Substitutions txt.

**Comment by gravydevsupreme** [comment]
Cannot seem to reproduce this issue. Will need concrete example and an easy way to reproduce.

**Comment by TokcDK** [comment]
> Cannot seem to reproduce this issue. Will need concrete example and an easy way to reproduce.

Ok. Here latest jp game where problem was detected:
<details>
  <summary>Test game name</summary>
[毛ガニ研究室] NTRハウス
  
</details>

But there is need savegame for normal test. I will post it. 

<details>
  <summary>Test save</summary>

[testsave.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3632169/testsave.zip)

path for saves:

%userappdata%\LocalLow\KeganiLab\NtrHouse

Also there found other problem when autotranslator is not translating effects of some items (velvet color). Items in right-up corner before last Settings button. In opened main char menu select Inventory button. But it was tested with different settings in autotranslator cfg file.

Here is Translation folder with substitutions and other:
[Translation.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3632207/Translation.zip)
</details>

**Comment by gravydevsupreme** [comment]
Think I fixed it all. There was a bug when a text was fully templated to not include anything that would be considered translatable. This is fixed.

I think the other issue you are seeing may simply be due to the character limit of 200 characters. You can increase that in the configuration file.

[XUnity.AutoTranslator-ReiPatcher-4.4.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3633001/XUnity.AutoTranslator-ReiPatcher-4.4.0.zip)

**Comment by TokcDK** [comment]
Looking like it is working now. Thanks. Also you are right about second problem it really was max chars limit.

**Comment by gravydevsupreme** [comment]
Perfect! Doubt I would have found this issue without your report. Thanks.

**Comment by TokcDK** [comment]
> Think I fixed it all. There was a bug when a text was fully templated to not include anything that would be considered translatable. This is fixed.
> 
> I think the other issue you are seeing may simply be due to the character limit of 200 characters. You can increase that in the configuration file.
> 
> [XUnity.AutoTranslator-ReiPatcher-4.4.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3633001/XUnity.AutoTranslator-ReiPatcher-4.4.0.zip)

Tested translation some time and found another case when substitutions is not using. For reproduce use same game with savegame and substitutions which I shared above but clean _AutoGeneratedTranslations.en.txt, 
after save will be loaded open character page where is displayed equipped items and over mouse on equipped velvet item in right-up corner(below yellow dagger) and then check _AutoGeneratedTranslations txt for appeared line

In this case I see full line without {{A}} and other markers which using for substitutions but they must be there because the string contains substitutions. And as you already said I set MaxCharactersPerTranslation=500 to make possible translate kind of lines.

**Comment by gravydevsupreme** [comment]
I will take a look at that as well. May also make some changes to make the ordering of parameters more consistent. Though this may "break" existing translations if modified.

**Comment by gravydevsupreme** [comment]
So this issue is not related to the latest version (4.4.0).

The issue is a weakness in my implementation that disallow outputting the "templated" text in a context that also includes rich text. It would require a bigger refactor to fix, so I am not going to do that right now.

If this is to provide a fully fledged manual translation, a different approach may be to use regexes to split up the translatable parts of the string, like described [here](https://github.com/bbepis/XUnity.AutoTranslator#splitter-regex).

**Note:** Same as with rich text, it is also not possible to output a "templated" text that has been split with a regex, so substitutions would have to be replaced with regular translations (which is just moving all the translations away from the _Substitutions file).

**Comment by gravydevsupreme** [comment]
Replaced by #56 as is describes this exact issue.
