### ISSUE TITLE
MaxCharactersPerTranslation

### ISSUE THREAD

**Issue by ziomik** [bbepis/XUnity.AutoTranslator#59]
Why was it limited to limit the maximum characters. I have a game that exceeds the maximum limit of 500! It seems to me that Google accepts up to 5000 characters, so I don't understand the reason for this limitation

`MaxCharactersPerTranslation=200  ;Max characters per text to translate. Max 500.`

**Comment by gravydevsupreme** [comment]
This limit is part of my peace of mind, really. Look at VNR, for instance, limiting the max number of characters to 149.

When using this plugin against untested games, it can theoretically get really unpredictable. The last thing I want is it bombarding any endpoint with 5000 characters/request with I don't know how many requests per second by a large amount of people. (Of course there are many mechanism in this plugin designed to prevent this, but limiting the max number of characters is one of them)

As soon as a version without such restrictions is released it is kinda hard to take it back and if the spam guards doesn't work properly, the people using the plugin could, unknowingly, become part of a network of 'DDOS' attackers against the translation endpoint. That could spell existential problems for the plugin as a whole (blocked by Google or worse).

The current limit of 500 is not entirely arbitrarily set, because I feel like that is probably the limit to what I would be comfortable redistributing the plugin with (and 500 is reaaaalllly stretching it).

I would not really mind increasing this limit, but at the same time I would want to find a way to ensure the plugin is never redistributed with such a configuration.

I'll see if I can find a way.

**Comment by ziomik** [comment]
Hello, thanks for you answer, while I see your point of view  and share the principle behind it, I think I might have a simple solution to the problem. 

What I was thinking about was to put a limit on the amount of requests time-wise, this way you would be able to prevent the consequences you mentioned above and still have the possibility for honest users to have the translation they need.

**Comment by gravydevsupreme** [comment]
Such restrictions already exists. But they exist to shutdown the plugin if the game itself behaves badly. The restrictions exists to protect users (and me) from badly behaving games, as there is no way for a user to behave badly.

Take a look at the version below. In that I have increased the limit for `MaxCharactersPerTranslation` from 500 to 1000.

[XUnity.AutoTranslator-ReiPatcher-4.5.0-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3735626/XUnity.AutoTranslator-ReiPatcher-4.5.0-custom.zip)
[XUnity.AutoTranslator-BepIn-5x-4.5.0-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3735627/XUnity.AutoTranslator-BepIn-5x-4.5.0-custom.zip)

**Comment by ziomik** [comment]
Oh thanks! I'll try it these days and I'll let you know. It is very useful as the game I am playing (Pathfinder Kingmaker) involves long dialogues.

**Comment by ziomik** [comment]
I confirm that it is much better now (considering the length of the texts of the game I am playing). Thanks again for your work!
