### ISSUE TITLE
Higurashi When They Cry

### ISSUE THREAD

**Issue by SmilingVLADISLAV** [bbepis/XUnity.AutoTranslator#60]
Can this be fixed? At the beginning of a sentence, two characters always appear.

Comparison:
![Image 027](https://user-images.githubusercontent.com/56461225/66881109-7801b980-f011-11e9-9437-6fb99f344060.png)

![Image 028](https://user-images.githubusercontent.com/56461225/66881115-7df79a80-f011-11e9-8a3c-980000212edd.png)

**Comment by gravydevsupreme** [comment]
This is a particularly nasty issue because not only is the game using the same component to display character name and text, but they input encoded text into that text component, which is why '\n' is not interpreted as a newline, like it should.

In order to provide a real fix for this game I would need to look into how the ADV engine used in that game handles updating text components and displays text.

For now you may be able to get away with adding a text file alongside the other translation files that contains 

```
sr:"^([\S\s]+)\\\\n([\S\s]+)$"=$1\n$2
sr:"^([\S\s]+)\\\\n([\S\s]+)\\\\n([\S\s]+)$"=$1\n$2\n$3
sr:"^([\S\s]+)\\\\n([\S\s]+)\\\\n([\S\s]+)\\\\n([\S\s]+)$"=$1\n$2\n$3\n$4
sr:"^([\S\s]+)\\\\n([\S\s]+)\\\\n([\S\s]+)\\\\n([\S\s]+)$\\\\n([\S\s]+)$"=$1\n$2\n$3\n$4\n$5
```

This may or may not reduce the quality of generated translations.

You should also remove all already generated translations.

**Comment by gravydevsupreme** [comment]
This is now solvable through the _Preprocessor.txt file.

Check the following https://github.com/bbepis/XUnity.AutoTranslator/issues/35#issuecomment-557924677
