### ISSUE TITLE
Log Error : A timeout error occurred while setting up GoogleTranslate TKK

### ISSUE THREAD

**Issue by lazism** [bbepis/XUnity.AutoTranslator#62]
I installed and used BepinEx on A.I. Shoujo, but translation didn't work.

I checked the logs,

[Warning:XUnity.AutoTranslator] A timeout error occured while setting up GoogleTranslate TKK. Using fallback TKK values installed.

The logs kept coming up, and when I looked up the other issues,

I tried to change it to "DisableCertificateValidation=True", but it still doesn't work. Is there a solution?

**Comment by gravydevsupreme** [comment]
This type of error is usually a sign that the IP-address is being temporarily blocked by Google. Perhaps you are on a shared IP?

In either case I would recommend just trying to change the translation source from Google to Bing, since the plugin should work just fine in that game.

While in game you can press ALT+0 to do this. Do this while a cursor is present, like on the main menu screen or similar.

**Comment by lazism** [comment]
Thank you for your answer.
I tried to change the source to Bing or Papago, but it still didn't work.
As you said, it seems to be related to IP. I recently changed my Internet service and there was an issue. The strange thing is Some of the previously well-functioning games still work and some 
 don't work.
I don't know the difference. Anyway, thank you for the answer.
