### ISSUE TITLE
Move the XUnity.ResourceRedirector back to BepInEx? some plugins need it.

### ISSUE THREAD

**Issue by ShinonomeHana** [bbepis/XUnity.AutoTranslator#66]
Some other plugins will use the parts `XUnity.ResourceRedirector` .
If a player can read Japanese, he/she will not install `AutoTranslator`. So they will not have the parts `XUnity.ResourceRedirector `, and it will make some plugins can't work properly.

**Comment by gravydevsupreme** [comment]
I understand the sentiment that everyone will not be installing the auto translation plugin, which is why I have given thought to simply adding a distribution of just the Resource Redirector on the release page.

Please note that the Resource Redirector implemented in this repository has no dependency on the AutoTranslator plugin, meaning it can be used without it. (you can simply delete the auto translator plugin and you're done)

This repository hosts code that is completely game-independent, where-as BepisPlugins are specific to the latest ILLUSION games (NOTE: The Koikatsu Resource Redirector was never a part of BepInEx, but instead a part of BepisPlugins). This means that this plugin cannot a dependency on BepisPlugins.

Of course, the Resource Redirector could also have its own repository entirely. This is arguably the most correct solution, but due to personal reasons I would rather avoid that, which is why just adding another distribution for just the Resource Redirector is probably what I am going to settle for.

**Comment by gravydevsupreme** [comment]
The latest release (4.6.4) now has a separate distribution for the Resource Redirector targeting BepInEx 5.x.

https://github.com/bbepis/XUnity.AutoTranslator/releases/tag/v4.6.4
