### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by djlaser** [bbepis/XUnity.AutoTranslator#72]
1.During the scene, virtually any (there are exceptions, but their not many), if nothing not now touch and not click "finish" (that completes scene), then characters will exchange replicas automatic, which are replaced by on their own, without click player. And they do it quite quickly and in the end the plugin does not have time to grab them (30 percent has time, but this is only worse).
2.Hello.Is it possible to completely remove the effect when there is first a Japanese text, and then in the eyes of the player is replaced by English?
This happens when scrolling text. The scroll utility is enabled, but nothing changes. You can immediately see the translated text.

**Comment by gravydevsupreme** [comment]
1. Please provide more information about the problem and the game it is happening in. I cannot understand what the problem is.
2. The first time an untranslated text appears, the plugin will obviously not be able to display the translated version of the text before it has had a chance to process a request towards the translation endpoint. Once it has been translated once, it is possible to show the translation while the text is "scrolling" in. Different engines implements such functionality differently, so in some games the default configuration work out of the box. In other cases, you may have to enable the option `GeneratePartialTranslations=True`. If there is a large amount of translations this may increase the memory usage of the plugin significantly.

**Comment by djlaser** [comment]
Hello the plugin does not have time to translate the text
which appears on the screen.

**Comment by gravydevsupreme** [comment]
A text that can be translated must appear on the screen without changing for at least one second before a translations request is sent out. This does not mean that texts that only appear shortly cannot be translated, just that it wont happen automatically. If a translation is already present in the cache, the translation would still occur.

This is an important spam prevention mechanism in the plugin, which is why it is not even a configurable parameter since changing it could cause the plugin to relentlessly queue translations if the text string of a text component is changed all the time (like would often be the case when text is "scrolling" into view).

Given that these texts appear for such a short amount of time, they must be rather short. Perhaps it is possible to simply provide a manual translation for them instead by simply writing them into a translation file (any .txt file in the `Translation\{Lang}\Text` directory).

This is obviously not entirely ideal, but since I don't know the game or the situation it occurs in, it is really the best I can suggest.

Another approach to outputting the untranslated text strings to the translation file would be to change the translator endpoint to `Passthrough`. This would output all encountered untranslated text strings to the translation file without performing a translation, skipping all spam prevention checks, but it would also disable any new translations while it is selected.

**Comment by djlaser** [comment]
Thanks
