### ISSUE TITLE
TextMeshPro fonts

### ISSUE THREAD

**Issue by djlaser** [bbepis/XUnity.AutoTranslator#82]
[Fonts1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4352944/Fonts1.zip)
ello dear gravydevsupreme!

Please write instructions or make video
 how to generate TextMeshPro fonts
and it is desirable to how to collect the generated script assestsbundle

Sincerely, djlaser
That's what I did and then did
Fonts1.zip

**Comment by gravydevsupreme** [comment]
It's difficult to provide straightforward guidance because it is different from version to version.

The biggest issue is which version of TMP that is used. Generally I would not expect TMP built with one version to work for a game built with another. So you need the version of TMP used in the specific game. This is not too hard if the version of Unity that is used is new (2018+), because in the later versions TMP is included as part of the engine as the package `Unity.TextMeshPro.dll`, which should be locatable in the Managed directory, if this is the case.

For any other versions you may be pretty much out of luck because you need an older version of the TextMeshPro tooling and those are not available for purchase anymore. So you need to obtain those tools in another way and I have no clue how you would go about obtaining that.

But it's not just versioning of TMP itself, it's also the versioning of the Unity Engine, because asset bundles build for one version of the engine are not automatically compatiable with other versions. There is some compatibility, but I cannot in any way account for how that works. I just know that sometimes it works, other times it doesn't.

So you would need to setup the Unity Editor for the correct version of the Engine and hope that is in-fact version 2018 or greater. (NOTE: Some games may be built with 2018 but not use the built-in package `Unity.TextMeshPro.dll` (check game folder), in which case you are pretty much out of luck as well).

Now if that is the case it is actually a fairly striaghtforward process. You simply create a new project and make sure the TextMeshPro package is installed in the project. I think that in some versions of Unity it is automatically installed, in other versions you can select it when you start a new project, and other times you may have to install it manually through menu options `Window -> Packages`. Find TextMeshPro in that list and install it. (NOTE: That there are different versions of this package, and you may have to install the one used in the game that you are targeting)

After you've installed it a new menu options becomes available under `Window -> TextMeshPro -> Font Asset Creator` (you may need to "Import TMP Essentials"). Here you will have to create the font asset based on a standard font file. Based on how big the font is and how many characters you want to include this can be a very timely process. I will refer to my [previous post](https://github.com/bbepis/XUnity.AutoTranslator/issues/57#issuecomment-569442090) to indicate what options I have used to create fonts (which includes most characters).

Once the font has been created it needs to be packaged into an asset bundle. This is also different based on which version of the Unity Editor that is being used.

In the newer versions of Unity you are able to get away without needing to provide any C# code, by installing the "Asset Bundle Browser" package, just like you would install the "TextMeshPro" package. This will give a new options under menu `Window -> AssetBundle Browser`.

There are three tabs: Configure, Build and Inspect

Under Configure, simply drag the font asset that was generated into the windows that opens. Any required dependencies will automatically be added as well.

This will generate an asset bundle that can be built. In order to build it, go to the Build tab. Leave target as Standalone Windows and take a note of (or change) where the asset bundle will be placed (Output Path). Then simply click "Build". That generates the asset bundle file that you can configure in the configuration file of this plugin.

I will reiterate that it is very difficult to provide completely specific guidance because it is different from version to version. Providing such guidance would likely just add even more confusion when what you see and what I provide in an eventual screenshot does not match.

As for your provided .zip file it looks like what you managed to do is generate the asset, which is the `Candaral SDF.asset` file. This is the one you would drag into the "Asset Bundle Browser".

**Comment by djlaser** [comment]
Thank you for answering. I'm closing up.
