### ISSUE TITLE
Visual novel- Fluffy Store - doesn't works

### ISSUE THREAD

**Issue by SerAsero** [bbepis/XUnity.AutoTranslator#83]
It doesn't hook any text:
![game](https://user-images.githubusercontent.com/63111126/78372814-0838b880-75ca-11ea-8f91-b2949f49c14a.PNG)
![config](https://user-images.githubusercontent.com/63111126/78372822-0b33a900-75ca-11ea-8188-130d7cf1071f.PNG)

**Comment by gravydevsupreme** [comment]
I will take a look at why the plugin does not catch the text in this game at next opportunity.

**Comment by gravydevsupreme** [comment]
As it turns out, this game uses a custom solution for UI drawing called [FairyGUI-unity](https://github.com/fairygui/FairyGUI-unity). In addition the developers has decided to use an obfuscation technique on parts of the code.

Even so, I managed to get it working, but due to obfuscation, updates may break compatibility (maybe).

Perhaps you can tell me if one of these works:

[XUnity.AutoTranslator-BepIn-5x-4.11.0-custom1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4433483/XUnity.AutoTranslator-BepIn-5x-4.11.0-custom1.zip)
[XUnity.AutoTranslator-ReiPatcher-4.11.0-custom1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4433484/XUnity.AutoTranslator-ReiPatcher-4.11.0-custom1.zip)

Thanks for the report and stay safe.

**Comment by SerAsero** [comment]
I tried with Reipatcher and it works! 
With all my heart, thank you for your fantastic support in this amazing project, I appreciate your efforts so much.

**Comment by gravydevsupreme** [comment]
Happy to help. Will release a new version with these changes probably within 1 to 2 weeks.
