### ISSUE TITLE
AutoTranslator UI ( ALT+0) on grey color

### ISSUE THREAD

**Issue by FranjeGueje** [bbepis/XUnity.AutoTranslator#90]
Hi all,

The AutoTranslator works for me on Pathologic 2 game ... but if open the AutoTranslator UI (ALT + 0), I only see a grey rectangle. The overlay doen't show correctly.

I've tried change all options in graphics configuration. I use the steam version, Win 10, and amd graphics card (drivers: 20.4.1).

What is the error? Someone with the same issue?

Thanks!! :)

![imagen](https://user-images.githubusercontent.com/64658346/80830201-dd517c80-8be8-11ea-964e-a7e375513cc5.png)

**Comment by gravydevsupreme** [comment]
Greetings,

It can be hard to tell exactly what is going wrong. The UI component of the plugin is based on an legacy UI system in Unity called IMGUI and some games like to strip away code that isn't used so that could be the reason.

Other than the UI, does the plugin function as expected in the game?

NOTE: With the exception of switching translator while the game is running there is not really any functionality in that UI that cannot be accessed through hotkeys. And the translator can also be changed through configuration.

**Comment by FranjeGueje** [comment]
Hi gravydevsupreme,

Yes, the plugin function as expected in the game. It works perfectly.
Ok, don't worry. I just wanted to make sure of this functionality, but it's not vital.

Thank you very much for your work.
