### ISSUE TITLE
Add versions of TryTranslate/TranslateAsync with scope parameter

### ISSUE THREAD

**Issue by GeBo1** [bbepis/XUnity.AutoTranslator#94]
Would it be possible to either add an optional `int scope` to `ITranslator.TryTranslate` and `ITranslator.TranslateAsync` or add a second set of methods that take scope?

I have a case where calling with a specific scope is required, and I'm doing it via harmony, but it would be cleaner/safer if there was an interface for it.

**Comment by gravydevsupreme** [comment]
If you're simply asking for a way to add a scope to the ITranslator interface with no expectations about how a newly generated translations would be outputted (unscoped), then it should be easy to make such a feature.

I would do this by simply adding a new overload to the interface to avoid breaking existing plugins.

BUT:
The plugin does not support adding scopes to automatically generated translations, and the "directive" syntax is explicitly disabled in the `OutputFile` (_AutoGeneratedTranslations.txt).

If you were to make a translation call with a scope, the resulting translation, if not found, when added to the cache, would not be scoped.

Obviously, that would not really make sense either, because if a translation was automatically generated by the plugin for one specific scope, it would be the same for a different scope, given the same translation endpoint.

**Comment by GeBo1** [comment]
That all sounds perfectly fine/reasonable to me

**Comment by gravydevsupreme** [comment]
Hello @GeBo1,

I added this in 4.11.3, which I just released.
