### ISSUE TITLE
 Does not translate games on the unity engine that are written in il2cpp

### ISSUE THREAD

**Issue by BurningDust98** [bbepis/XUnity.AutoTranslator#98]
I would like to play Power Rangers Battle For The Grid with translation, but the problem was that there were no files to translate because the game is written in il2cpp, if there is at least some way to play with the translation, I will be grateful for the help as thanks in advance
![image](https://user-images.githubusercontent.com/67206011/85210964-4f268680-b34d-11ea-89c5-81d986dd7cdd.png)

**Comment by gravydevsupreme** [comment]
The plugin does not currently support IL2CPP.

Previous issues has also asked regarding support for IL2CPP games, but in all of those I have dismissed the idea entirely.

In the future, however, I may try to implement support for it (based on this project [MelonLoader](https://melonwiki.xyz/#/), which is still in its beta stages). But right now, and in the immediate future it will not be supported.

**Comment by BurningDust98** [comment]
Thank you very much for the answer and good luck and patience in the development of this system, and if you are implementing or trying to implement, I will be happy

**Comment by gravydevsupreme** [comment]
I have a very preliminary version of the plugin that works with IL2CPP through MelonMod.

Many features have been stripped in order to get it to work properly, but it still all the basic functionality.

[XUnity.AutoTranslator-MelonMod-4.12.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4996148/XUnity.AutoTranslator-MelonMod-4.12.0.zip) **(IL2CPP only!)**

I cannot guide you in how to setup MelonLoader, though. Current versions seems to only work in 64-bit processes and as of this release I have only tried it in one game.

**Comment by seelebrn** [comment]
Thank you very much!

I ended up making an English mod for this particular game, but that's great news :)

**Comment by cacarasa** [comment]
someone knows how to install the XUnity AutoTranslator MelonMod? Thanks

**Comment by gravydevsupreme** [comment]
Issue now tracked in pinned issue.
